//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craftersmine.SteamGridDBNet.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("craftersmine.SteamGridDBNet.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad request to SteamGridDB. Invalid ID, asset, parameter, etc..
        /// </summary>
        internal static string Exception_BadRequest {
            get {
                return ResourceManager.GetString("Exception.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expected date time object value..
        /// </summary>
        internal static string Exception_ExpectedDateTimeObject {
            get {
                return ResourceManager.GetString("Exception.ExpectedDateTimeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expected integer token type in JSON..
        /// </summary>
        internal static string Exception_ExpectedIntegerValue {
            get {
                return ResourceManager.GetString("Exception.ExpectedIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request to SteamGridDB forbidden. Probably because you don&apos;t own item action on which you want to perform..
        /// </summary>
        internal static string Exception_Forbidden {
            get {
                return ResourceManager.GetString("Exception.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image stream appears to be empty..
        /// </summary>
        internal static string Exception_ImageStreamIsEmpty {
            get {
                return ResourceManager.GetString("Exception.ImageStreamIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unix epoc starts January 1st, 1970..
        /// </summary>
        internal static string Exception_InvalidDateTime {
            get {
                return ResourceManager.GetString("Exception.InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid file MIME type. Supported MIME types are {0}..
        /// </summary>
        internal static string Exception_InvalidMimeType {
            get {
                return ResourceManager.GetString("Exception.InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This type of item doesn&apos;t support style &quot;{0}&quot;.
        /// </summary>
        internal static string Exception_InvalidStyleSelected {
            get {
                return ResourceManager.GetString("Exception.InvalidStyleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only one selected platform supported.
        /// </summary>
        internal static string Exception_MoreThanOnePlatformSelected {
            get {
                return ResourceManager.GetString("Exception.MoreThanOnePlatformSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only one style supported to select for uploading item..
        /// </summary>
        internal static string Exception_MoreThanOneStyleSelected {
            get {
                return ResourceManager.GetString("Exception.MoreThanOneStyleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requested grid/hero/icon/logo/game not found on SteamGridDB..
        /// </summary>
        internal static string Exception_NotFound {
            get {
                return ResourceManager.GetString("Exception.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are rate limited by the server! Retry after: {0}.
        /// </summary>
        internal static string Exception_RateLimited {
            get {
                return ResourceManager.GetString("Exception.RateLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unauthorized request to SteamGridDB. Probably due to missing or invalid API key..
        /// </summary>
        internal static string Exception_Unauthorized {
            get {
                return ResourceManager.GetString("Exception.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown Exception occurred..
        /// </summary>
        internal static string Exception_Unknown {
            get {
                return ResourceManager.GetString("Exception.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown error has occurred while downloading image..
        /// </summary>
        internal static string Exception_UnknownImageException {
            get {
                return ResourceManager.GetString("Exception.UnknownImageException", resourceCulture);
            }
        }
    }
}
